#####################  Development ###########################
# FROM node:14.16.1-alpine As development
FROM postgres:13.3
# RUN apk add --no-cache alpine-conf && \
#     setup-timezone -z Asia/Kathmandu